---
title: 'So you want to teach a workshop!'
author: Alice Walsh
date: '2020-08-15'
slug: workshop_tips_2020
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

# Teaching a workshop with R-Ladies

At R-Ladies Philly, we have held over 40 events since our first meetup in January 2018! 

Some of our events are networking focused like our happy hour events. Other events are lightning talks, formal presentations, or code & coffee meetups to hang out and work together. We also organize collaborative projects where members work together on real datasets for local non-profits. Last, but not least, we hold many interactive workshops where members can learn R skills for free in a supportive environment.

To support and encourage more new workshop leaders, we have collected some tips and tricks below. We expect to evolve and update this guide over time (especially as we learn more about hosting successful online events). Therefore, we will maintain the guide online at this [GitHub repository](https://github.com/rladiesPHL/workshop-tips), where others can contribute.


## Checklist 

1. Develop your content (see tips below)
1. Practice or ask others to test it out (does it take 5 minutes? 5 hours?)
1. If needed, identify volunteers to help troubleshoot with attendees or answer questions
1. Check that the venue has internet available 
1. Share any instructions and required materials ahead of the event
1. Share materials online (GitHub is preferred)

## Tips  

1. Consider how much time you want to spend doing exercises and interactive portions versus delivering introductions and content.
1. There are several options for how to deliver content:
	+ Slides with live demo and walk-through
	+ Slides with exercises
	+ Chalk/Whiteboard with R exercises
	+ Use Rmd instead of slides
1. Consider using RStudio Cloud (https://rstudio.cloud/learn/guide)
	+ *There is a default max number of users for a project, but you can contact RStudio to request additional capacity.*
1. If many non-base or uncommon packages are needed, consider providing instructions to install these packages ahead of time or pre-install them in RStudio Cloud.
1. Share code ahead of time using GitHub.
	+ If you are new to GitHub, we can help you set up a repository and add materials. We have done this for other workshop leads - no problem.
1. One great approach is to get people excited by showing them the end result and then backing up to the beginning to show them how to get there. See more [here](https://speakerdeck.com/minecr/let-them-eat-cake-first-0a3bbf75-f6f1-42d5-8d2f-ac2ff741611f).
1. Timing: prepare less than you think you need. Build in breaks for questions and to allow participants to catch up.
1. Consider varying the difficulty of content - maybe for each part there can be an easy bit and a stretch bit for advanced attendees or for people to try after the event.
1. *Virtual events*: For online events, there are several ways to handle Q&A. Platforms like Zoom have a chat function for asking questions. The webinar feature of Zoom has a special Q&A feature. We have found that questions in the chat can be difficult to manage by the presenter. Therefore, we like having a dedicated host or assistant to collect questions and either answer them in real-time or collect to share with the presenter during breaks. To do this, the event organizers can create a Q&A google doc. See this [example](https://bit.ly/304YP7x).
1. Understand that things will definitely go wrong and that is ok :)
1. Data availability considerations: you will probably be using some dataset for demonstration.   
	+ You should check whether this data can be shared with this audience and is free and open to use for educational purposes. 
	+ Base R and some R packages have datasets packaged with them (e.g., mtcars). These are good choices because they are easy for everyone to use.
	+ If your dataset is very large and would need to be downloaded, consider modifying to use a small subset of the data that can be easily shared.
	+ We recommend choosing a fun or simulated dataset to keep the focus of the workshop on the concepts and methods. It can be challenging to present on a dataset from a field you are not an expert in.


## Some additional resources  

1. https://ctb.ku.edu/en/table-of-contents/structure/training-and-technical-assistance/workshops/main

Some previous R-Ladies Philly workshops for inspiration:

+ Elea on A/B testing: https://www.youtube.com/watch?v=QXpYtM-Zlxg
+ Mary on Spatial Data: https://github.com/rladies/meetup-presentations_philadelphia/tree/master/2018_11/Spatial_Data_Basics_Presentation
+ Jake on Data Visualization: https://github.com/rjake/r-ladies-data-viz
+ Mine on R/Shiny: https://github.com/rladies/meetup-presentations_philadelphia/blob/master/2018_10_October.md

# Get in touch!
If you are interested in leading a workshop with us, get in touch! We welcome workshop leaders of all experience levels. The organizing team takes care of all the logistics (event promotion, organization, setup, etc.) so that you can focus on the workshop content.

The organizing team can be reached at philly@rladies.org. We also encourage you to sign up on our [mentor/speaker directory](https://rladiesphilly.shinyapps.io/mentorship/). 

We cannot thank enough all the volunteers and organizers that have contributed to create new content for our events! 

*This post was authored by Alice Walsh. For more information contact philly@rladies.org*