---
title: 'June 2020: Intro to R Workshop'
author: Alice Walsh
date: '2020-06-28'
slug: j2020-june-recap
categories: []
tags: []
authors: []
header:
  caption: ''
  image: ''
  preview: yes
---

## Our June Virtual Workshop

R-Ladies Philly continues to host free online events during the Coronavirus pandemic. On June 9th, we hosted an introduction to R workshop for beginners with a featured lighting talk.

Thanks to our new [YouTube channel](https://www.youtube.com/channel/UCPque9BaFV9p0hcgImrYBzg), you can view a recording of the entire event online.

## "6 R Packages to Add to Your Workflow" by Jinyi Kuang

We kicked off the event with a lightning talk by Jinyi Kuang. Her slides are available on her GitHub account [here](https://github.com/jinyikuang000/r-ladies-talk).

Jinyi highlighted 6 packages that can boost your productivity in R. For example, [plotly](https://images.plot.ly/plotly-documentation/images/r_cheat_sheet.pdf?_ga=2.144655730.634097270.1588348056-452179466.1588348056) allows you to make beautiful interactive graphics.


## Intro to R Workshop by Tess Cherlin

Before the workshop, Tess created this [useful resource](https://github.com/rladies/meetup-presentations_philadelphia/blob/master/2020_06/R%20Studio%20Download%20Tutorial%202020.pdf) to guide new R users through how to install R and RStudio for the first time.

The content for the main workshop is available online [here](https://github.com/alldayscientess/RLadies).

The example data for this workshop were taken from the [Women, Minorities, and Persons with Disabilities in Science and Engineering Report](https://ncses.nsf.gov/pubs/nsf19304/data).

## Continue to learn!

We hope that new R users will jump into using R and continue to attend R-Ladies events! For some immediate next steps, here are some free online resources:

+ Swirl: [https://swirlstats.com](https://swirlstats.com)
+ R for Data Science: [https://r4ds.had.co.nz](https://r4ds.had.co.nz)
+ R4DS online community: [https://rfordatasci.com](https://rfordatasci.com)
+ [http://Learningstatisticswithr.com](http://Learningstatisticswithr.com)
+ Tidymodels: [https://www.tidymodels.org/learn/](https://www.tidymodels.org/learn/)
+ Troubleshooting errors: [Guide from the CCDL](https://github.com/AlexsLemonade/training-modules/blob/master/intro-to-R-tidyverse/00b-debugging_resources.md)
+ Look for a mentor! R-Ladies Philly has started a [mentor/speaker directory](https://rladiesphilly.shinyapps.io/mentorship/) where you can find someone to connect with or volunteer yourself

Don't forget that R-Ladies Philly also has a Slack workspace where you can join the conversation to ask the R questions you have always wanted to ask and learn more about upcoming events. You can join [here](https://bit.ly/join-rladies-slack-2020).

## Thank you
Many thanks to our great presenters [Jinyi Kuang](https://twitter.com/jinyikuang) and [Tess Cherlin](https://twitter.com/alldayscientess).  
Thank you to R-Ladies Global for hosting the zoom meeting.

*This post was authored by Alice Walsh. For more information contact philly@rladies.org*